NumPy Exercises

Exercise 1

Create a NumPy array and display its shape, number of dimensions, size, and datatype.

In [1]:

import numpy as np

In [2]:
arr1 = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Size:", arr1.size)
print("Datatype:", arr1.dtype)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Datatype: int64


Exercise 2

Create the following arrays using NumPy:

a 3×3 matrix of zeros

a 2×4 matrix of ones

a 3×3 identity matrix

In [4]:
zeros = np.zeros((3,3))
ones = np.ones((2,4))
identity = np.eye(3)

print("\nZeros matrix:\n", zeros)
print("\nOnes matrix:\n", ones)
print("\nIdentity matrix:\n", identity)


Zeros matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones matrix:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Exercise 3

Generate numbers from 1 to 12 using np.arange() and reshape them into a 3×4 matrix.

In [5]:
arr2 = np.arange(1,13)
reshaped = arr2.reshape(3,4)

print("\nOriginal array:", arr2)
print("\nReshaped matrix:\n", reshaped)


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Exercise 4

Perform vector operations on two arrays:

addition

element-wise multiplication

dot product

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("\nAddition:", a + b)
print("Element-wise multiplication:", a * b)
print("Dot product:", np.dot(a,b))


Addition: [5 7 9]
Element-wise multiplication: [ 4 10 18]
Dot product: 32


Exercise 5

Create a 3×3 matrix and perform slicing operations:

extract the first row

extract the first column

extract the top-left 2×2 submatrix

In [7]:
matrix = np.arange(1,10).reshape(3,3)

print("\nMatrix:\n", matrix)
print("First row:", matrix[0])
print("First column:", matrix[:,0])
print("Top-left 2x2:\n", matrix[0:2,0:2])


Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
First column: [1 4 7]
Top-left 2x2:
 [[1 2]
 [4 5]]


Exercise 6

Combine two matrices using:

horizontal stacking

vertical stacking

In [8]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

horizontal = np.hstack((A,B))
vertical = np.vstack((A,B))

print("\nHorizontal Stack:\n", horizontal)
print("\nVertical Stack:\n", vertical)


Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
